title: FFMPEG Transcoder on OKE
schemaVersion: 1.1.0
version: "20210907"
locale: "en"
groupings:
- title: "Deployment Type"
  variables: 
  - use_remote_exec
  visible: false
- title: "SSH Key"
  variables:
  - ssh_provided_public_key
- title: "Availabilty Domain"
  variables:
  - availability_domain
- title: "VCN Options"
  variables:
  - useExistingVcn
  - myVcn
  - vcn_dns_label
  - custom_cidrs
  - VCN_CIDR
  - edge_cidr
  - private_cidr
- title: "OKE Cluster Options"
  variables:
  - create_new_oke_cluster
  - cluster_name
  - kubernetes_version
  - cluster_endpoint_config_is_public_ip_enabled
  - OKESubnet
  - existing_oke_cluster_id
- title: "OKE Node Pool Configuration"
  variables:
  - oke_nodepool_name
  - oke_nodepool_shape
  - oke_nodepool_size
  - oke_node_ocpu
  - oke_node_memory
  - oke_namespace
  - kube_label
- title: "OKE Cluster Autoscaling Configuration"
  variables:
  - cluster_autoscaling
  - oci_cluster_autoscaler_image
  - min_worker_nodes
  - max_worker_nodes
  - cpu_request_per_job
- title: "OKE Registry Configuration"
  variables:
  - registry
  - repo_name
  - registry_user
  - image_label
- title: "Object Storage Bucket Configuration"
  variables:
  - src_bucket
  - dst_bucket
- title: "OCI Streaming Service Configuration"
  variables:
  - stream_name
  - stream_partitions
  - stream_retention_in_hours
- title: "Vault Configuration"
  variables:
  - vault_secret_id
- title: "OCI-MySQL Configuration"
  variables:
  - mysql_admin_username
  - mysql_admin_password
  - mysql_shape
  - db_name
  - db_user
  - db_password
  - enable_backups
- title: "Staging Server Configuration"
  variables:
  - public_edge_node
  - bastion_name
  - bastion_shape
  - edgeSubnet
- title: "Transcoding Configuration"
  variables:
  - project_name
  - ffmpeg_config
  - ffmpeg_stream_map
- title: "CDN Configuration"
  variables:
  - hls_stream_url
- title: "Pre-Defined"
  variables:
  - region
  - compartment_ocid
  - tenancy_ocid
  - meta_db_type
  - cluster_options_add_ons_is_kubernetes_dashboard_enabled
  - cluster_options_admission_controller_options_is_pod_security_policy_enabled
  visible: false

variables:
  use_remote_exec: 
    type: boolean
    title: "Use Remote Execution"
    description: "By default this deployment will use a remote execution that requires ssh access to the staging VM using it's public IP.  If remote access using a public IP is disabled in your VCN then CloudInit deployment must be used instead. This allows to deploy the stack on a network that is not internet facing. CloudInit deployment has not been implemented yet"
    default: true
    
  ssh_provided_public_key:
    type: string
    title: "SSH Public Key"
    description: "Copy/Paste the contents of your SSH Public Key"
    required: true 
    default: ""
    visible:
      not:
        - use_remote_exec

  create_new_oke_cluster:
    type: boolean
    title: "Create OKE Cluster"
    description: "Check to deploy a new OKE cluster.  If you do not create an OKE cluster you must provide the OCID of an existing one."
    default: true

  existing_oke_cluster_id:
    type: string
    title: "Existing OKE Cluster ID"
    description: "Input the existing OKE cluster ID here for deployment."
    visible:
      not:
        - create_new_oke_cluster

  cluster_endpoint_config_is_public_ip_enabled:
    type: boolean
    title: "Create Public Endpoint"
    description: "By default this template will create a secure Kubernetes API endpoint which is on a private subnet accessible only inside the VCN.  By checking this box, you choose to deploy the cluster to a PUBLIC subnet and create a PUBLICLY ACCESSIBLE endpoint.  This will also deploy FSS and OCI-MySQL assets to the same PUBLIC subnet."
    default: false
    visible: create_new_oke_cluster

  kubernetes_version:
    type: enum
    enum:
    - "v1.20.8"
    - "v1.19.7"
    - "v1.19.2"
    - "v1.18.10"
    title: "Kubernetes Version"
    description: "Choose the version of Kubernetes to deploy"
    required: true
    default: "v1.20.8"
    visible: create_new_oke_cluster

  cluster_name:
    type: string
    title: "OKE Cluster Name"
    description: "Name the OKE Cluster"
    required: "true"
    default: "tc-cluster"
    visible: create_new_oke_cluster

  useExistingVcn:
    type: boolean
    title: "Use Existing VCN"
    description: "Click to use existing VCN, otherwise VCN and Subnets will be created"
    required: true
    default: false

  myVcn:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select Existing VCN"
    dependsOn:
      compartmentId: compartment_ocid
    visible: useExistingVcn
    required: true

  custom_cidrs:
    type: boolean
    title: "Customize Network CIDRS"
    description: "Click to customize CIDR ranges, only applicable when creating VCN as part of deployment"
    required: true
    default: false
    visible:
      not:
        - useExistingVcn

  OKESubnet:
    type: oci:core:subnet:id
    title: "OKE Subnet"
    description: "Select Subnet for OKE cluster"
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: myVcn
    visible: useExistingVcn
    required: true

  edgeSubnet:
    type: oci:core:subnet:id
    title: "Edge Subnet"
    description: "Select Subnet for Bastion.  If using remote exec, ensure that this is a public subnet or deployment will fail."
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: myVcn
    visible: useExistingVcn
    required: true

  availability_domain:
    type: oci:identity:availabilitydomain:name
    title: "Availability Domain"
    description: "Select AD"
    dependsOn:
      compartmentId: compartment_ocid
    required: true

  VCN_CIDR:
    type: string
    title: "VCN CIDR"
    description: "Customize VCN top level CIDR"
    visible: custom_cidrs

  edge_cidr:
    type: string
    title: "Edge Subnet CIDR"
    description: "Customize Edge Subnet CIDR, ensure this fits in VCN CIDR range."
    visible: custom_cidrs

  private_cidr:
    type: string
    title: "Private Subnet CIDR"
    description: "Customize Private Subnet CIDR, ensure this fits in VCN CIDR range."
    visible: custom_cidrs

  vcn_dns_label:
    type: string
    title: "VCN DNS Label"
    description: "Set the VCN DNS label to be used when creating VCN.  Default is 'tcvcn' which sets the VCN domain to 'tcvcn.oraclevcn.com'"
    visible:
      not:
        - useExistingVcn

  meta_db_type:
    type: enum
    title: "Transcoder Database"
    description: "Pick which database to use."
    enum:
    - "OCI Mysql"
    required: true
    visible: false

  oke_nodepool_name:
    type: string
    title: "OKE Node Pool Name"
    description: "Define the node pool name, no spaces"
    required: true
    visible: create_new_oke_cluster

  oke_nodepool_shape:
    type: oci:core:instanceshape:name
    title: "OKE Node Pool Shape"
    description: "Define node pool shape"
    required: true
    visible: create_new_oke_cluster
    dependsOn:
      compartmentId: compartment_ocid
    default: "VM.Standard.E3.Flex"

  oke_nodepool_size:
    type: int
    title: "OKE Node Pool size"
    description: "Enter a value, minimum 1"
    min: 1
    default: 1
    required: true
    visible: create_new_oke_cluster

  oke_node_ocpu:
    type: int
    title: "OKE Node OCPU number"
    description: "Enter a value, minimum 1"
    min: 1
    default: 2
    visible: create_new_oke_cluster

  oke_node_memory:
    type: int
    title: "OKE Node memory in GB"
    description: "Enter a value, minimum 16"
    min: 1
    default: 32
    visible: create_new_oke_cluster

  oke_namespace:
    type: string
    title: "OKE Namespace"
    default: "transcode"
    required: true

  kube_label:
    type: string
    title: "Kube Label"
    default: "transcode"
    required: true

  cluster_autoscaling:
    type: boolean
    title: "Cluster Autoscaling"
    default: true
    required: true
  
  oci_cluster_autoscaler_image:
    type: string
    title: "Cluster Autoscaler Image"
    description: "Set this to the target region you are deploying to. For the list available OCI Cluster Autoscaler images see https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm"
    default: "iad.ocir.io/oracle/oci-cluster-autoscaler:1.19-2021.03"
    required: true
    visible: cluster_autoscaling

  min_worker_nodes:
    type: int
    title: "Minimum Number of Worker Nodes"
    description: "Enter a value, minimum 1"
    min: 1
    max: 1000
    default: 1
    required: true
    visible: cluster_autoscaling

  max_worker_nodes:
    type: int
    title: "Maximum Number of Worker Nodes"
    description: "Enter a value, minimum 1"
    min: 1
    max: 1000
    default: 5
    required: true
    visible: cluster_autoscaling

  cpu_request_per_job:
    type: string
    title: "vCPU weight for 1 Transcoding Job "
    default: "1.5"
    required: true
    visible: cluster_autoscaling

  registry:
   type: string
   title: "OCI Registry"
   description: "Set this to the target region you are deploying to"
   default: "iad.ocir.io"
   required: true

  repo_name:
    type: string
    title: "Repo Name"
    required: true

  registry_user:
    type: string
    title: "OCI Registry Username"
    description: "Set this to your username for OCI Registry"
    required: true
    default: "oracleidentitycloudservice/<username>"

  image_label: 
    type: string
    title: "Transcoder Image Label"
    default: "1.3"
    required: true

  src_bucket: 
    type: string
    title: "Source Bucket Name"
    default: "<name of the bucket where media files are uploaded>"
    required: true

  dst_bucket: 
    type: string
    title: "Destination Bucket Name"
    default: "<name of the bucket where transcoded files are stored>"
    required: true

  stream_name: 
    type: string
    title: "Name of OCI Streaming Queue"
    default: "transcode-stream"
    required: true

  stream_partitions: 
    type: int
    title: "Number of Stream Partitions"
    description: "Enter a value, minimum 1"
    min: 1
    max: 10
    default: 1
    required: true

  stream_retention_in_hours: 
    type: int
    title: "Number of Stream Partitions"
    description: "Enter a value, minimum 1"
    min: 24
    max: 168
    default: 24
    required: true

  vault_secret_id:
    type: string
    title: "Vault Secret ID"
    description: "OCI vault secret ID where authentication key is stored - it is used for authenticatoin when pushing/pulling images to/from OCIR registry. Set it to secret OCID where you store authentication token that is used to push/pull images from OCIR"
    default: "ocid1.vaultsecret.oc1.iad.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    required: true

  mysql_admin_username:
    type: string
    title: "OCI MySQL username"
    description: "Enter a username for the MySQL database admin user"
    default: "mysqladmin"
    required: true

  mysql_admin_password:
    type: password
    title: "OCI MySQL password"
    description: "The password for the administrative user. The password must be between 8 and 32 characters long, and must contain at least 1 numeric character, 1 lowercase character, 1 uppercase character, and 1 special (nonalphanumeric) character."
    required: true

  mysql_shape:
    type: enum
    enum:
    - "VM.Standard.E2.1"
    - "VM.Standard.E2.2"
    - "VM.Standard.E2.3"
    - "VM.Standard.E2.4"
    title: "OCI MySQL instance shape"
    description: "Shape of the OCI MySQL intance"
    default: "VM.Standard.E2.2"

  enable_backups:
    type: boolean
    title: "Enable MySQL backups"
    description: "Enable MySQL backups for OCI MySQL database"
    default: false

  db_name:
    type: string
    title: "Transcoder Database Name"
    default: "tc"
    required: true

  db_user:
    type: string
    title: "Transcoder Database Username"
    default: "tc"
    required: true

  db_password:
    type: password
    title: "Transcoder Database password"
    required: true

  stg_server_name:
    type: string
    title: "Staging Server Name"
    default: "stg-server"
    required: true
    
  stg_server_shape:
    type: oci:core:instanceshape:name
    title: "Staging Server Instance Shape"
    dependsOn:
      compartmentId: compartment_ocid
    default: "VM.Standard2.1"
    required: true

  public_edge_node:
    type: boolean
    title: "Deploy Staging Server to Public Subnet"
    default: true
    required: true
    visible:
      not:
        - use_remote_exec

  project_name:
    type: string
    title: "Project Name"
    required: true

  ffmpeg_config:
    type: string
    title: "FFMPEG Configuration"
    required: true

  ffmpeg_stream_map:
    type: string
    title: "FFMPEG Stream Map"
    required: true
  
  hls_stream_url:
    type: string
    title: "HLS Stream URL"
